mir-protocol/plonky

src/field.rs
This makes field multiplications almost 3x faster.
=> Use Montgomery reductions instead of Barrett reductions

src/curve.rs, src/tweedledee_curve.rs, src/tweedledum_curve.rs
I added ZETA for the Tweedledee and Tweedledum curves, along with tests verifying that the endomorphism works. 
Here is the Sage code used to generate the ZETA values:
```python
def get_zetta(q, b):
E = EllipticCurve(GF(q), [0, b])
r = E.order()
assert(is_prime(r))
K.<x> = GF(q)[]
Kr.<xr> = GF(r)[]
zettas_base = [a[0] for a in (x^2 + x + 1).roots()]
zettas_scalar = [a[0] for a in (xr^2 + xr + 1).roots()]
zetta_scalar = zettas_scalar[0]
G = E.random_point()
for a in zettas_base:
if ZZ(zetta_scalar)*G == E(a*G.xy()[0], G.xy()[1]):
return ZZ(a), ZZ(zetta_scalar)
q = 28948022309329048855892746252171976963322203655955319056773317069363642105857
b = 5
z_b, z_s = get_zetta(q, b)
E = EllipticCurve(GF(q), [0, b])
G = E.random_point()
assert(z_s * G == E(z_b * G.xy()[0], G.xy()[1])) 
```
=> Adding ZETA for endomorphism on Tweedle curves.

src/plonk.rs, src/plonk_gates.rs
The code is a bit weird because I didn't want to require `WitnessGenerator`s to be cloneable. So the generator-related data structures store indices into `self.generators`, which is a `Vec` of `Box`ed generators, and then we borrow as needed.
=> Implement generate_witness

src/plonk.rs, src/plonk_recursion.rs
We already had code to partition wires based on copy constraints, so this is just converting those partitions to a map `sigma` from `[kn]` to `[kn]`, then computing `S_sigma`. `S_sigma` has the same values, it's just structured as a separate polynomial for each wire.
=> Compute sigma, S_sigma, and C(S_sigma)

src/plonk.rs
This code was assuming that `generator_indices_by_deps` would contain an entry for every target, but some targets are not dependencies of any generator.
=> Fix witness generation

src/curve_msm.rs, src/fft.rs, src/main.rs, src/plonk.rs, src/plonk_gates.rs, src/plonk_recursion.rs, src/plonk_util.rs
- Add a `ConstantGate` which copies a constant to one of its wires. We were using `BufferGate` for this earlier, but `add_blinding_gate` expected `BufferGate` to be a no-op (i.e. enforce no constraints).
- Add a few assertions to catch errors earlier with more helpful errors
- Misc small fixes, like indices being in the wrong order
=> Misc prover fixes to get William's test working

Cargo.toml, src/mds.rs, src/plonk_gates.rs
This is a bit tricky since, as far as I know, Rust doesn't provide an easy way to store static data that is specific to a generic type (like `F` in our case). To work around that, I've used a single cache map with the field's TypeId in the key and "serialized" field data in the value. Let me know if you see a more elegant solution though.
=> Cache MDS matrices

src/plonk_gates.rs, src/plonk_util.rs
I `#[ignore]`d the tests since they're expensive, but they can be run like this:
cargo test low_degree -- --ignored
=> Add tests for low-degreeness of each constraint

src/circuit_builder.rs, src/plonk.rs, src/plonk_gates.rs
ArithmeticGate loses a constant, but its callers weren't using its third constant  anyway (i.e. it was always zero). All gate mechanics remain the same apart from that.
Tested with
cargo test low_degree -- --ignored
=> Reorganize prefix tree to fix constraint degrees

src/bin/recursion.rs, src/plonk_proof.rs, src/plonk_recursion.rs
`proof_to_public_inputs` isn't really needed since these values are also derived by the circuit (from the inputs given by `ProofTarget::populate_witness` and `OldProofTarget::populate_witness`). Arguably the redundancy could be useful for catching some errors, but I'd prefer to minimize redundancy to keep the code simpler.
=> Derive public inputs in a generic way

src/bin/msms.rs, src/bin/recursion.rs, src/circuit_builder.rs, src/plonk.rs, src/plonk_challenger.rs, src/plonk_proof.rs, src/plonk_recursion.rs, src/verifier.rs, src/witness.rs, tests/prove_and_verify_recursive.rs, tests/prove_and_verify_vk.rs
This should compute `halo_us` properly. (I'm avoiding "IPA challenges" now because of the ambiguity.)
The main method is now failing with a PI related error, but I think it makes sense. The recursive circuit expects its inner proof to publish assumptions as PIs, but the dummy proof has no assumptions or PIs.
=> Some fixes relating to our use of the Halo endo

src/circuit_builder.rs, src/gates/mod.rs, src/plonk.rs, src/plonk_challenger.rs, src/plonk_recursion.rs, src/rescue.rs, src/witness.rs
This may save us some evaluations of the permutation, since we no longer have to save one of the outputs and pass it in as an input to the next hash. The sponge already has "memory" of previous messages via its capacity element.
Inspired by @daira's talk: https://www.youtube.com/watch?v=IQVGIqcdxL4&t=50m05s
=> Modify Challenger to use a duplex sponge pattern

Cargo.toml, benches/fft.rs, src/fft.rs
Tested with `cargo bench ifft/2_exp_18`. There seems to be a bit of speedup, although timing is pretty noisy on my machine, so it's hard to measure accurately.
=> Avoid copying in IFFT code, and add benchmarks

Cargo.toml, plookup/.gitignore, plookup/Cargo.toml, plookup/README.md, plookup/src/lib.rs, plookup/src/openings.rs, plookup/src/plookup.rs, plookup/src/proof.rs, plookup/src/table.rs, plookup/src/verifier.rs, plookup/tests/plookup.rs
Added Plookup support. Currently this can be used to prove that a set of committed values is a subset of a public lookup table. We will then be able to integrate this into Plonky and add these checks for some circuits where a lookup table can save lots of gates, e.g., bit operations.
=> Added plookup

plookup/src/lib.rs, plookup/src/openings.rs, plookup/src/plookup.rs, plookup/src/proof.rs, plookup/src/verifier.rs, src/bigint/bigint_arithmetic.rs, src/circuit_builder.rs, src/fft.rs, src/field/tweedledee_base.rs, src/field/tweedledum_base.rs, src/gates/mod.rs, src/halo.rs, src/lib.rs, src/plonk.rs, src/plonk_challenger.rs, src/plonk_proof.rs, src/plonk_util.rs, src/poly_commit.rs, src/polynomial.rs, src/verifier.rs, tests/prove_and_verify.rs
This PR adds a `Polynomial` struct that wraps a vector of coefficients. This provides a type-level distinction between polynomials in coefficient vs evaluation form, and more generally between a polynomial and a vector of field elements. It also allows for a more object-oriented design for handling polynomial, e.g. `p.add(&q)` instead of `polynomial_addition(&p, &q)`.
=> New polynomial API

src/circuit_builder.rs, src/circuit_builder_bigint.rs, src/circuit_builder_ordering.rs, src/foreign_field.rs, src/gates/base_4_sum.rs, src/lib.rs, src/target.rs, src/util.rs, src/witness.rs, tests/prove_and_verify.rs
Currently foreign field addition takes ~400 gates and multiplication takes ~600 gates, most of which is range checking via `Base4SumGate`. The reduction is the most expensive part, so batch operations (like adding many products of foreign field elements) should be much more efficient, since they can do a single reduction. There's definitely room for improvement if we want to optimize further; I've just been focused on simplicity. Of couse plookup could also be integrated for much cheaper range checking.
A few design questions that came up:
- How should we fit bounded types into the type hierarchy? Originally I had `Target`, `BoundedTarget`, `BigIntTarget`, and `BoundedBigIntTarget`. It was getting a bit cluttered with bounded and unbounded versions of various methods, so I merged the …
=> Circuit code for bigint and foreign field arithmetic

src/bin/recursion.rs, src/circuit_builder.rs, src/foreign_field.rs, src/plonk.rs, src/plonk_proof.rs, src/plonk_util.rs, src/polynomial.rs, src/verifier.rs, src/witness.rs, tests/prove_and_verify.rs, tests/prove_and_verify_recursive.rs
This PR removes the `output_pis` flag used currently in the prover so that proofs no longer contain the openings at the public input gates.
Note: I haven't modified `ProofTarget` yet.
=> Remove public inputs from proof

src/circuit_bigint.rs, src/circuit_builder.rs, src/circuit_curve.rs, src/circuit_foreign_field.rs, src/circuit_ordering.rs, src/curve/curve.rs, src/gates/arithmetic.rs, src/gates/base_4_sum.rs, src/gates/buffer.rs, src/gates/constant.rs, src/gates/curve_add.rs, src/gates/curve_dbl.rs, src/gates/curve_endo.rs, src/gates/mod.rs, src/gates/public_input.rs, src/gates/rescue_a.rs, src/gates/rescue_b.rs, src/partition.rs, src/plonk.rs, src/plonk_challenger.rs, src/plonk_proof.rs, src/plonk_recursion.rs, src/plonk_util.rs, src/target.rs, src/witness.rs
Added field and curve types to target structs, e.g., `Target` is now `Target<F>` where `F: Field`.
This allows for compile-time checks that the code is handling values in the correct field.
=> Typed targets

src/field/bls12_377_base.rs, src/field/field.rs, src/field/tweedledee_base.rs, src/field/tweedledum_base.rs
There were a couple things causing compiler errors --
- The macro calls were using non-qualified names, as in `test_arithmetic!(TweedledumBase)`, but `TweedledumBase` is no longer in scope in the context of the new submodule. I switched to qualified names, as in `test_arithmetic!(crate::TweedledumBase)`.
- I needed to add back the `Field` imports in modules like `bls12_377_base::test`. Previously it was pulled in by `test_arithmetic!`, but not anymore since the macro imports it into a submodule.
=> Separate module for arithmetic tests

Cargo.toml, src/fft.rs, src/serialization.rs, src/verifier.rs
- Change `#[serde(skip)]` to `#[serde(default, skip_serializing_if = "Option::is_none")]` for both FFT and MSM precomputations, along with helper functions to set these attributes to `None`.
- Move from `bincode` to `serde_cbor`, since `bincode` does not support `#[serde(default)]`, and `serde_cbor` yields smaller serialized data.
=> Fully serialized vk

src/field/bls12_377_base.rs, src/field/bls12_377_scalar.rs, src/field/tweedledee_base.rs, src/field/tweedledum_base.rs, src/plonk.rs, src/plonk_proof.rs, src/serialization.rs
Since `Field` is already a subtrait of `Serialize` and `DeserializeOwned`, we don't need Serde to add its own bounds like `where F: Serialize`. The redundant bounds would normally be harmless, but they cause an error due to a compiler bug: https://github.com/rust-lang/rust/issues/41617
=> Prevent Serde from adding redundant bounds on `F`

src/bin/recursion.rs, src/circuit_builder.rs, src/gates/public_input.rs, src/lib.rs, src/plonk.rs, src/plonk_recursion.rs, src/serialization.rs, src/target.rs, src/verifier.rs, src/witness.rs, tests/prove_and_verify.rs
I've implemented the functionalities to put the public inputs at the end of the circuits and not at the beginning as it is now.
I haven't modified `plonk_recursion.rs` except to make it compile.
=> Move public inputs to the end of circuits

src/field/field.rs, src/field/mod.rs, src/field/monty.rs, src/field/tweedledee_base.rs, src/field/tweedledum_base.rs, src/lib.rs
This PR implements faster modular squaring using the Montgomery CIOS method. The improvement over multiplication comes from observing that only half of the 'off-diagonal' pairs of digits need to be multiplied because of the symmetry of the input.
Main references were [Acar's PhD thesis](https://www.microsoft.com/en-us/research/wp-content/uploads/1998/06/97Acar.pdf) and a [blog post by the Goff team](https://hackmd.io/@zkteam/modular_multiplication) (though I haven't yet implemented the improvement they are talking about at the latter link).
Benchmarking on my laptop suggests this implementation costs 60-70% of the time of the existing Montgomery multiplication function. Specifically multiplication takes around 48ns and squaring around 33ns. (Both drop by a further 5-10% when the …
=> Issue 70: Fast modular squaring

src/field/field.rs
It isn’t required to check each bit of number from left to right to calculate the number of bits. You just need to check bits from right to left until you meet zero limbs. The changes below include little improvements without rewriting result.
Below are time measurements:
| version        | time (ns)      |
| ------------- |:-------------:|
| old    | 188.41 |
| new      | **87.340** |
=> Field: num bits improvement

benches/bls12_base.rs, benches/bls12_scalar.rs, benches/tweedledee_base.rs, src/field/field.rs
We have slightly accelerated the exponentiation algorithm. The Rust compiler does not unwrap a 64-range cycle, so a fixed check has no benefit. That's why **IF** statement has been taken out of cycle to improve performance.
Time measurements:
| version        | time (us)      |
| ------------- |:-------------:|
| old    | 9.7351 |
| new      | **9.1447** |
=> Field::exp improvement

src/field/field.rs, src/field/tweedledee_base.rs
We have added an improvement to avoid regularly transformation field_to_biguint for each iteration inside of cycle by using field_to_biguint transformation once outside of cycle.
Below are time measurements:
| version        | time (us)      |
| ------------- |:-------------:|
| old    | 17.390 |
| new      | **12.291** |
=> Field: k-th root improvement

benches/bls12_g1.rs, src/curve/bls12_377_curve.rs, src/curve/curve.rs
According to the fact that output of the double operation should be AffinePoint and _affine -> projective -> affine_ transformation is resource-intensive changes were done to fix it. Also, the changes below include little improvements without rewriting results.
Old implementation:
* 11 additions and 12 multiplications for addition operation at projective coordinates;
* 2 multiplications and 1 inverse element search for transition from projective to affine coordinates.
New implementation:
* 1 inverse element search, 7 additions and 4 multiplications.
Speed comparison of the old and new implementations is presented below:
| version        | time (us)       |
| ------------- |:-------------:|
| old    | 8.1654  |
| new      | **7.4816** |
=> Curve: double improvement

src/curve/curve.rs, src/curve/tweedledee_curve.rs, src/curve/tweedledum_curve.rs
We have added an additional check to prevent attacks in case when the discriminant is equal to zero. You can read more  [this](https://www.dima.unige.it/~morafe/MaterialeCTC/p80-menezes.pdf) and [this](https://mathworld.wolfram.com/EllipticDiscriminant.html)
=> Add check discriminant

src/field/field.rs
The `kth_root_consistent_with_exp` test added in #93 includes some inputs that are invalid for some fields; in particular the test fails on the `Bls12377Scalar` and `Bls12377Base` fields. (These are not currently used AFAIK, but they helped to identify this issue in this case.)
Specifically the degrees specified [here](https://github.com/mir-protocol/plonky/pull/93/files#diff-76cc81a01fafe86577994ea59bd7367a25c82a95900cd38596dca072bb7a4ec9R748) include the value 5, however `x^5` is not a permutation on Bls12377Scalar so `kth_root()` panics. Similarly, degrees 7 and 13 that are in the test do not give permutations of either of the BLS12-377 fields.
The fix is to check the condition required for a given degree to give a permutation, namely that the degree is coprime to q-1 where q is the …
=> Fix/expand test input for kth root test.

src/curve/mod.rs, src/curve/pallas_curve.rs, src/curve/vesta_curve.rs, src/field/mod.rs, src/field/pallas_base.rs, src/field/vesta_base.rs, src/serialization.rs
This PR implements support for the [Pasta curve pair](https://electriccoin.co/blog/the-pasta-curves-for-halo-2-and-beyond/) which provide some benefits over the Tweedle* curve pair.
This PR does not attempt to implement any of the performance improvements mentioned in the aforementioned reference; the benefits such are likely to be fairly modest.
Most of the work was just converting the published constants into Montgomery form and pasting them into the right slots. This means that there is some additional duplication with the other field and curve implementations; this will be refactored in due course. The only exception to this was the choice of the `ZETA` and `ZETA_SCALAR` parameters which are not mandated by the Pasta curves, just their properties; so a choice was made and set in the …
=> Implement support for the Pasta curves
